apiVersion: v1
kind: Namespace
metadata:
  name: external
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerhost
  namespace: external
  labels:
    k8s-app: dockerhost
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: dockerhost
  template:
    metadata:
      labels:
        k8s-app: dockerhost
    spec:
      containers:
        - name: dockerhost
          image: qoomon/docker-host
          securityContext:
            capabilities:
              add: ["NET_ADMIN", "NET_RAW"]
---
apiVersion: v1
kind: Service
metadata:
  name: dockerhost
  namespace: external
spec:
  clusterIP: None
  selector:
    k8s-app: dockerhost
